[servers]
debian-base ansible_host=192.168.122.93 ansible_user=admin ansible_ssh_private_key_file=./adminkey ansible_become=true ansible_ssh_common_args='-o IdentitiesOnly=yes'
debian-base2 ansible_host=192.168.122.143 ansible_user=admin ansible_ssh_private_key_file=./adminkey ansible_become=true ansible_ssh_common_args='-o IdentitiesOnly=yes'
[webservers]
debian-base2 ansible_host=192.168.122.143 ansible_user=admin ansible_ssh_private_key_file=./adminkey ansible_become=true ansible_ssh_common_args='-o IdentitiesOnly=yes'