---
- name: Configure SSH
  ansible.builtin.import_tasks: ssh.yml

- name: Create administrative user
  ansible.builtin.import_tasks: user.yml

- name: Configure auditd
  ansible.builtin.import_tasks: auditd.yml
